version: '3.8'
services:
  db:
    image: postgres:16
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: run/secrets/db_password
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql
    secrets:
      - db_password

  frontend:
    depends_on:
      - backend
    image: emil25/lime-link-client
    container_name: lime_link_next_js
    environment:
      NEXT_PUBLIC_CLIENT_ID: /run/secrets/client_id
      NEXT_PUBLIC_CLIENT_SECRET: /run/secrets/client_secret
      NEXT_PUBLIC_JWT_SECRET: /run/secrets/jwt_secret
      NEXT_PUBLIC_SERVER_URL: http://localhost:8080
    ports:
      - 80:80
      - 3000:3000
    secrets:
      - client_id
      - client_secret
      - jwt_secret
  
  backend:
    depends_on:
      - db
    image: emil25/lime-link-server
    container_name: lime-link-express_js
    environment:
      DATABASE_URL: /run/secrets/db_url
      PORT: 8080
      JWT_SECRET: /run/secrets/jwt_secret
    ports:
      - 8080:8080
    secrets:
      - db_url
      - jwt_secret

secrets:
  client_id:
    file: ./secrets/client_id.txt
  client_secret:
    file: ./secrets/client_secret.txt
  db_password:
    file: ./secrets/db_passwd.txt
  jwt_secret:
    file: ./secrets/jwt_secret.txt
  db_url:
    file: ./secrets/database_url.txt



  